services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: excusatron_php
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env.prod.local
    ports:
      - "8090:80"
    volumes:
      - uploads_data:/var/www/html/public/uploads
      - var_data:/var/www/html/var

  db:
    image: postgres:16-alpine
    container_name: excusatron_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  uploads_data:
  var_data:
