<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260614114328 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE classic_excuse (estimated_delay INT DEFAULT NULL, is_reusable BOOLEAN NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE emergency_excuse (emergency_level INT NOT NULL, requires_proof BOOLEAN NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE excuse (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, status VARCHAR(255) NOT NULL, urgency_level INT NOT NULL, credibility_score INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, author_id INT NOT NULL, context_id INT NOT NULL, category_id INT NOT NULL, tone_id INT NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_623AD9F0F675F31B ON excuse (author_id)');
        $this->addSql('CREATE INDEX IDX_623AD9F06B00C1CF ON excuse (context_id)');
        $this->addSql('CREATE INDEX IDX_623AD9F012469DE2 ON excuse (category_id)');
        $this->addSql('CREATE INDEX IDX_623AD9F0CF1344F6 ON excuse (tone_id)');
        $this->addSql('CREATE TABLE excuse_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE excuse_context (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE excuse_tone (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, risk_level INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE professional_excuse (target_recipient VARCHAR(255) DEFAULT NULL, professional_tone VARCHAR(255) DEFAULT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE classic_excuse ADD CONSTRAINT FK_D4C6EB34BF396750 FOREIGN KEY (id) REFERENCES excuse (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE emergency_excuse ADD CONSTRAINT FK_A1B65949BF396750 FOREIGN KEY (id) REFERENCES excuse (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE excuse ADD CONSTRAINT FK_623AD9F0F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE excuse ADD CONSTRAINT FK_623AD9F06B00C1CF FOREIGN KEY (context_id) REFERENCES excuse_context (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE excuse ADD CONSTRAINT FK_623AD9F012469DE2 FOREIGN KEY (category_id) REFERENCES excuse_category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE excuse ADD CONSTRAINT FK_623AD9F0CF1344F6 FOREIGN KEY (tone_id) REFERENCES excuse_tone (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE professional_excuse ADD CONSTRAINT FK_2284AB2CBF396750 FOREIGN KEY (id) REFERENCES excuse (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE classic_excuse DROP CONSTRAINT FK_D4C6EB34BF396750');
        $this->addSql('ALTER TABLE emergency_excuse DROP CONSTRAINT FK_A1B65949BF396750');
        $this->addSql('ALTER TABLE excuse DROP CONSTRAINT FK_623AD9F0F675F31B');
        $this->addSql('ALTER TABLE excuse DROP CONSTRAINT FK_623AD9F06B00C1CF');
        $this->addSql('ALTER TABLE excuse DROP CONSTRAINT FK_623AD9F012469DE2');
        $this->addSql('ALTER TABLE excuse DROP CONSTRAINT FK_623AD9F0CF1344F6');
        $this->addSql('ALTER TABLE professional_excuse DROP CONSTRAINT FK_2284AB2CBF396750');
        $this->addSql('DROP TABLE classic_excuse');
        $this->addSql('DROP TABLE emergency_excuse');
        $this->addSql('DROP TABLE excuse');
        $this->addSql('DROP TABLE excuse_category');
        $this->addSql('DROP TABLE excuse_context');
        $this->addSql('DROP TABLE excuse_tone');
        $this->addSql('DROP TABLE professional_excuse');
    }
}
