<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260614155351 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE badge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, icon VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE excuse_tag (excuse_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (excuse_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_CCC9686C45731166 ON excuse_tag (excuse_id)');
        $this->addSql('CREATE INDEX IDX_CCC9686CBAD26311 ON excuse_tag (tag_id)');
        $this->addSql('CREATE TABLE excuse_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, excuse_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_671FE12B45731166 ON excuse_comment (excuse_id)');
        $this->addSql('CREATE INDEX IDX_671FE12BF675F31B ON excuse_comment (author_id)');
        $this->addSql('CREATE TABLE excuse_rating (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, excuse_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A4B293045731166 ON excuse_rating (excuse_id)');
        $this->addSql('CREATE INDEX IDX_A4B2930F675F31B ON excuse_rating (author_id)');
        $this->addSql('CREATE TABLE excuse_validation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(50) NOT NULL, comment TEXT DEFAULT NULL, validated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, excuse_id INT NOT NULL, validator_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_76F1857345731166 ON excuse_validation (excuse_id)');
        $this->addSql('CREATE INDEX IDX_76F18573B0644AEC ON excuse_validation (validator_id)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, message TEXT NOT NULL, is_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CAA76ED395 ON notification (user_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, color VARCHAR(30) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE user_badge (user_id INT NOT NULL, badge_id INT NOT NULL, PRIMARY KEY (user_id, badge_id))');
        $this->addSql('CREATE INDEX IDX_1C32B345A76ED395 ON user_badge (user_id)');
        $this->addSql('CREATE INDEX IDX_1C32B345F7A2C2FC ON user_badge (badge_id)');
        $this->addSql('ALTER TABLE excuse_tag ADD CONSTRAINT FK_CCC9686C45731166 FOREIGN KEY (excuse_id) REFERENCES excuse (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE excuse_tag ADD CONSTRAINT FK_CCC9686CBAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE excuse_comment ADD CONSTRAINT FK_671FE12B45731166 FOREIGN KEY (excuse_id) REFERENCES excuse (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE excuse_comment ADD CONSTRAINT FK_671FE12BF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE excuse_rating ADD CONSTRAINT FK_A4B293045731166 FOREIGN KEY (excuse_id) REFERENCES excuse (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE excuse_rating ADD CONSTRAINT FK_A4B2930F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE excuse_validation ADD CONSTRAINT FK_76F1857345731166 FOREIGN KEY (excuse_id) REFERENCES excuse (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE excuse_validation ADD CONSTRAINT FK_76F18573B0644AEC FOREIGN KEY (validator_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B345A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B345F7A2C2FC FOREIGN KEY (badge_id) REFERENCES badge (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE excuse_tag DROP CONSTRAINT FK_CCC9686C45731166');
        $this->addSql('ALTER TABLE excuse_tag DROP CONSTRAINT FK_CCC9686CBAD26311');
        $this->addSql('ALTER TABLE excuse_comment DROP CONSTRAINT FK_671FE12B45731166');
        $this->addSql('ALTER TABLE excuse_comment DROP CONSTRAINT FK_671FE12BF675F31B');
        $this->addSql('ALTER TABLE excuse_rating DROP CONSTRAINT FK_A4B293045731166');
        $this->addSql('ALTER TABLE excuse_rating DROP CONSTRAINT FK_A4B2930F675F31B');
        $this->addSql('ALTER TABLE excuse_validation DROP CONSTRAINT FK_76F1857345731166');
        $this->addSql('ALTER TABLE excuse_validation DROP CONSTRAINT FK_76F18573B0644AEC');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE user_badge DROP CONSTRAINT FK_1C32B345A76ED395');
        $this->addSql('ALTER TABLE user_badge DROP CONSTRAINT FK_1C32B345F7A2C2FC');
        $this->addSql('DROP TABLE badge');
        $this->addSql('DROP TABLE excuse_tag');
        $this->addSql('DROP TABLE excuse_comment');
        $this->addSql('DROP TABLE excuse_rating');
        $this->addSql('DROP TABLE excuse_validation');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE user_badge');
    }
}
